OBS_STR = "observation"
OBS_STATE = f"{OBS_STR}.state"
OBS_IMAGE = f"{OBS_STR}.image"
OBS_IMAGES = f"{OBS_STR}.images"
OBS_LANGUAGE = f"{OBS_STR}.language"
OBS_LANGUAGE_TOKENS = f"{OBS_LANGUAGE}.tokens"
OBS_LANGUAGE_ATTENTION_MASK = f"{OBS_LANGUAGE}.attention_mask"

ACTION = "action"
ACTION_IS_PAD = "action_is_pad"
EPISODE_SUCCESS = "episode.success"
EPISODE_QUALITY = "episode.quality"
SUBTASK_LABEL = "subtask.label"
SUBGOAL_IMAGE = "subgoal.image"
FUTURE_IMAGE = "future.image"
